### ISSUE TITLE
crashes of obs 29.1.3 on win10

### ISSUE THREAD

**Issue by LemonSylvan** [occ-ai/obs-localvocal#44] opened 2023-10-25 00:19 UTC
No matter what options I choose, OBS crashes as soon as I activate the plugin filter =(
I attach the obs log and crash log. feels like something is wrong with whisper.dll obs-localvocal.dll on my PC.
[2023-10-24 15-56-59.txt](https://github.com/obs-ai/obs-localvocal/files/13143856/2023-10-24.15-56-59.txt)
[2023-10-24 15-57-22.txt](https://github.com/obs-ai/obs-localvocal/files/13143860/2023-10-24.15-57-22.txt)
[Crash 2023-10-24 15-57-15.txt](https://github.com/obs-ai/obs-localvocal/files/13143964/Crash.2023-10-24.15-57-15.txt)
[Crash 2023-10-24 15-57-54.txt](https://github.com/obs-ai/obs-localvocal/files/13143966/Crash.2023-10-24.15-57-54.txt)
![screen1](https://github.com/obs-ai/obs-localvocal/assets/148921426/2538968e-808a-4c56-ba7f-c551240e5391)

**Comment by royshil** [comment] 2023-10-25 01:49
Thanks for the info
It actually looks like the plugin filter was initially loaded successfully
But then it's trying to load again and at that point it crashed.

Do you have the filter in more than one source?
If so please stick to just one source for right now just to check.

Also it looks like at the start the filter is ok. So can you please load the filter and then restart OBS?
I want to see if the initial filter load work out

**Comment by LemonSylvan** [comment] 2023-10-25 03:47
I have the filter on just one microphone source.
Here how it works exactly: as long as the filter applied to the source, but not turned on, obs is not crashing.
After I make it "visible" click on the eye icon next to the filter, nothing happens for 3-5 seconds and then obs crashes =(
I tried to set every option in "subtitle output", it crashes anyway even with "no output" option.

Going to film the whole process on a phone since I can't record it with obs :D
I can provide any other info that might be helpful in ~6-8 hours when I am back.
Thx in advance!

**Comment by royshil** [comment] 2023-10-29 05:59
@LemonSylvan i fixed in #47 
can you check the plugin build artifacts 
https://github.com/obs-ai/obs-localvocal/actions/runs/6681562436#artifacts
to see if it solved your problem?
for me it was solved on windows with a folder that has special characters

**Comment by LemonSylvan** [comment] 2023-10-30 09:15
@royshil do I reinstall the plugin?
I have no cyrillic fonts in the obs path I think, but will double check!

**Comment by LemonSylvan** [comment] 2023-10-30 10:24
[Crash 2023-10-30 13-19-55.txt](https://github.com/obs-ai/obs-localvocal/files/13203971/Crash.2023-10-30.13-19-55.txt)
[2023-10-30 13-17-00.txt](https://github.com/obs-ai/obs-localvocal/files/13203972/2023-10-30.13-17-00.txt)


https://github.com/obs-ai/obs-localvocal/assets/148921426/7d0dfe2c-387b-41b2-929c-0c865d7cc16c

Filmed the whole process from enabling the mic filter to complete obs crash. OBS logs attached.
sorry for the video quality, filimed on the phone

**Comment by LemonSylvan** [comment] 2023-11-01 14:45
any ideas what I should try to make it work?
got a subtitles request for my job, your plugin would perfectly fit, trying to make it work =(

**Comment by royshil** [comment] 2023-11-01 14:49
@LemonSylvan have you used https://github.com/occ-ai/obs-localvocal/actions/runs/6681562436#artifacts to install the plugin with the possible fix?

**Comment by LemonSylvan** [comment] 2023-11-02 02:58
> @LemonSylvan have you used https://github.com/occ-ai/obs-localvocal/actions/runs/6681562436#artifacts to install the plugin with the possible fix?

yeah, unfortunately video and crash logs are with the new version installed already.
![image](https://github.com/occ-ai/obs-localvocal/assets/148921426/121eab84-2a66-4159-b005-c13855c3259e)

**Comment by royshil** [comment] 2023-11-02 06:38
@LemonSylvan can you change the log level to "INFO" in the filter settings?
lets see the extended logs then after you enable the filter

**Comment by LemonSylvan** [comment] 2023-11-02 13:55
![image](https://github.com/occ-ai/obs-localvocal/assets/148921426/3a6d5477-3cf0-4771-b674-2e6a06ddb536)
[2023-11-02 16-53-10.txt](https://github.com/occ-ai/obs-localvocal/files/13239571/2023-11-02.16-53-10.txt)
[Crash 2023-11-02 16-53-58.txt](https://github.com/occ-ai/obs-localvocal/files/13239574/Crash.2023-11-02.16-53-58.txt)
Did, but have not noticed anything difference in logs. Am I even uloading the right logs?(

> @LemonSylvan can you change the log level to "INFO" in the filter settings? lets see the extended logs then after you enable the filter

**Comment by royshil** [comment] 2023-11-02 14:26
@LemonSylvan everything seems to be fine. it crashes on Whisper.cpp processing...
Do you have an Intel or AMD machine?

**Comment by LemonSylvan** [comment] 2023-11-02 14:43
@royshil will try it asap, when I get to my workstation studio. Much thanks for solving this! I can reply here later or should we close this thread?

**Comment by royshil** [comment] 2023-11-02 15:32
@LemonSylvan lets keep it open until we verify this works on another computer

**Comment by royshil** [comment] 2023-11-04 20:59
@LemonSylvan i'd like to close this issue. any further insights?

**Comment by royshil** [comment] 2023-11-13 22:02
closing, found root cause

**Closed by royshil** 2023-11-13 22:02 UTC

**Comment by LemonSylvan** [comment] 2023-11-14 14:24
@royshil thanks for the info. had no chances to test it on another PC yet
